name: ${parent.name}
version: ${project.parent.version}-b${buildNo}
main: ${project.groupId}.${parent.name}
api-version: 1.13
description: ${project.parent.description}
website: https://www.spigotmc.org/resources/solidfix.54103/
author: qruet

commands:
  solidfix:
    aliases: [ solidf, sf ]
    description: Provides information about this plugin.
