name: SolidFix
version: 2.3-b13
main: dev.qruet.solidfix.SolidFix
api-version: 1.13
description: A lightweight fix to prevent bad block packets from ruining your players' gaming experience. This
        plugin is no longer maintained, use at your own risk!
website: https://www.spigotmc.org/resources/solidfix.54103/
author: qruet

commands:
  solidfix:
    aliases: [ solidf, sf ]
    description: Provides information about this plugin.
